server:
     port: 8090
spring:
     datasource:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/jtdb
          username: root
          password: 123456  
mybatis:
    typeAliasePackge: com.mybatis
    mapperLocations: classpath:mappers/*.xml
logging:
  level: 
    com.mybatis.mapper: debug